## Contents
- 날짜 변환 : to_datetime, to_timestamp, to_period
- 날짜 생성 : date_range, period_range, date_range
- 날짜 인덱싱, 필터링, 집계, 속성 접근, 정렬

python, numpy, pandas 날짜 타입 비교 및 정리

- datetime은 python 설치 시 기본적으로 내장된 라이브러리로, 날짜를 쓸 것인지, 시간을 쓸 것인지, 날짜시간을 합쳐쓸 것인지에 따라 클래스가 분화되어 있는 것이 특징. 예를들어 '2021-3-16'을 표시하고 싶으면 date 클래스를 사용하고, '2021-3-16 12:34:21'를 표시하고 싶으면 'datetime' 클래스를 사용합니다.
- 반면 datetime64나 Timestamp는 각각 numpy, pandas 라이브러리에서 새로 정의한 날짜시간 클래스입니다. 이 둘은 numpy, pandas를 설치해야만 이용할 수 있고, 한 클래스로 날짜, 시간, 날짜시간을 모두 정의할 수 있는 것이 특징
- 날짜, 시간 타입은 일반적인 정수, 실수끼리 연산할 때와 달리 단위를 가지고 있는 점 때문에 시간의 차이를 저장하는 별도의 클래스가 있다는 특징. 이를 timedelta(타임델타)라고 하는데, 날짜, 시간은 특정 시점의 시각을 표시하는 용도이고(2021년 3월 16일), 타임델타는 기간 또는 시간 차이를 표시하는 용도(5일)

파이썬 datetime 모듈
- 기본 개념: datetime 모듈은 날짜 및 시간을 다루는 기본적인 클래스들(date, time, datetime, timedelta, tzinfo)을 제공
- 날짜 생성 및 조작: 특정 날짜를 생성하거나 날짜 간의 차이를 계산하는 등의 기능을 수행
- 포맷팅: strftime()을 사용하여 날짜를 문자열로, strptime()을 사용하여 문자열을 날짜로 변환
- 시간대 처리: 시간대를 처리하는 기능을 포함하고 있지만, 별도의 라이브러리(pytz 등)의 도움이 필요

판다스
- 시계열 데이터 처리에 최적화: 판다스는 시계열 데이터 처리에 특화되어 있으며, 대량의 날짜 데이터를 빠르고 효율적으로 처리할 수 있다.
- DateTimeIndex: 판다스는 DateTimeIndex를 제공하여 시계열 데이터의 인덱싱과 슬라이싱을 간편하게 한다.
- 시간대 처리: 판다스는 내장된 시간대 처리 기능을 제공하며, 시간대 변환을 손쉽게 할 수 있다.
- 날짜 데이터 변환 및 조작: to_datetime() 함수로 다양한 형식의 날짜 문자열을 datetime 객체로 변환할 수 있다. 또한, resample, asfreq 등의 메서드로 시계열 데이터의 빈도를 변경하는 등 다양한 날짜 관련 조작을 지원.
- 통합된 데이터 처리: 판다스는 DataFrame이나 Series 내의 날짜 데이터를 다룰 때, 다른 데이터 유형과의 통합된 처리가 가능.

포인트
- 파이썬 datetime: 날짜 및 시간의 기본적인 처리에 적합하며, 작고 단순한 날짜 관련 작업에 이상적이다.
- 판다스: 대규모 데이터셋에서 복잡하고 고급 시계열 데이터 처리에 적합하며, 데이터 분석과 관련된 다양한 기능을 제공한다.
- 사용 사례에 따라 적절한 도구를 선택하는 것이 중요. 작은 규모의 기본적인 날짜 연산에는 datetime을, 복잡한 데이터셋과 시계열 분석에는 판다스를 사용하는 것이 일반적.

Python의 datetime 모듈을 사용한 날짜 처리 예시. 이 예제들은 datetime 모듈을 사용하여 날짜 및 시간 데이터를 다루는 기본적인 방법을 보여준다.

- 현재 날짜 및 시간 얻기: datetime.now()를 사용.
- 특정 날짜 및 시간 생성: datetime 객체를 직접 생성.
- 날짜 간 차이 계산: timedelta를 사용.
- 날짜 포맷팅: 날짜를 문자열로 변환하거나 문자열로부터 날짜를 파싱.
- 날짜와 시간 요소 접근: 날짜의 연도, 월, 일 등을 접근.

판다스를 사용한 날짜 처리의 예. 이 예제들은 판다스가 시계열 데이터를 어떻게 다룰 수 있는지 보여준다.

- 날짜 범위 생성: pd.date_range()를 사용하여 날짜 범위를 생성.
- 날짜 변환: 문자열을 pd.to_datetime()을 사용하여 날짜 객체로 변환.
- 시계열 데이터 생성: 날짜를 인덱스로 사용하는 시계열 데이터를 생성.
- 날짜 기반 필터링: 특정 날짜 조건을 만족하는 데이터를 필터링.
- 시계열 데이터 리샘플링: 월별 평균 등으로 데이터를 리샘플링.
- 이 코드를 실행하면, 판다스를 사용하여 날짜 데이터를 다양하게 처리하는 방법을 확인할 수 있다. 날짜 범위 생성, 날짜 변환, 시계열 데이터 처리 등은 데이터 분석에서 매우 유용하게 활용.

In [5]:
# 문자열 형식의 날짜를 datetime 형식으로 변환한여 처리
import pandas as pd
date_str = '2022-01-01'
date_dt = pd.to_datetime(date_str)
print(date_dt)
# 연도/날짜만 출력
print(date_dt.date())
# 시분초
print(date_dt.time())
print(type(date_dt))

2022-01-01 00:00:00
2022-01-01
00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [7]:
# 날짜 변환
dates = ['2020-01-01','2020-01-05','2020-01-10']
date_objects = pd.to_datetime(dates)
print("날짜 객체:", date_objects)
date_only_list = [date.date() for date in date_objects]
print(date_only_list)

날짜 객체: DatetimeIndex(['2020-01-01', '2020-01-05', '2020-01-10'], dtype='datetime64[ns]', freq=None)
[datetime.date(2020, 1, 1), datetime.date(2020, 1, 5), datetime.date(2020, 1, 10)]

In [19]:
# date_only_list 를 ['2020-01-01','2020-01-05','2020-01-10']으로 출력
date_str = [date.strftime('%Y-%m-%d') for date in date_only_list]
print(date_str)

['2020-01-01', '2020-01-05', '2020-01-10']

In [6]:
# pd.date_range 함수는 일정한 간격으로 날짜 범위를 생성하는 데 사용
# pd.date_range 함수는 pandas에서 제공하지만 내부적으로 numpy의 날짜/시간 타입인 datetime64를 사용
date_range = pd.date_range(start = '2022-01-1', end = '2022-01-10')
print(date_range)

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10'],
              dtype='datetime64[ns]', freq='D')

In [24]:
# 날짜를 인덱스로 설정하여 데이터프레임을 구성하면 날짜를 기준으로 데이터 조작이 용이
data = {'date':['2022-01-01','2022-01-02','2022-01-03'], 'value':[1,2,3]}
df = pd.DataFrame(data)
df.set_index('date',inplace=True)
print(df)

            value
date
2022-01-01      1
2022-01-02      2
2022-01-03      3

In [25]:
df.index.name = None
print(df)

            value
2022-01-01      1
2022-01-02      2
2022-01-03      3

In [28]:
# 날짜를 인덱스로 설정한 데이터프레임에서는 특정 기간의 데이터를 쉽게 인덱싱하고 슬라이싱
# 특정 날짜의 데이터 선택
print(df.loc['2022-01-02'],'\n')

# 날짜 범위 슬라이싱
print(df['2022-01-01':'2022-01-02'])

value    2
Name: 2022-01-02, dtype: int64

            value
2022-01-01      1
2022-01-02      2

In [30]:
# 불리언 조건식을 사용하여 날짜 범위를 필터링
date_range = pd.date_range(start = '2020-01-01', end = '2020-01-10')
date_series = pd.Series(date_range)
fd = date_series[(date_series >= '2020-01-01') & (date_series <= '2020-01-03')]
print(df)

            value
2022-01-01      1
2022-01-02      2
2022-01-03      3

In [35]:
pd.date_range(start = '2022-01-01', periods=10, freq = 'B')
pd.date_range(start = '2022-01-01', periods=10, freq = 'W')

DatetimeIndex(['2022-01-02', '2022-01-09', '2022-01-16', '2022-01-23',
               '2022-01-30', '2022-02-06', '2022-02-13', '2022-02-20',
               '2022-02-27', '2022-03-06'],
              dtype='datetime64[ns]', freq='W-SUN')

In [32]:
# pandas는 주어진 주기(일,월,분기 등)에 따라 데이터를 리샘플링할 수 있는 기능을 제공
# resample 메소드를 사용하면 다양한 방법으로 데이터를 집계
# freq = 'D" 일 단위
date_range = pd.date_range(start = '2022-01-01', periods=10, freq = 'D')
data = {'value': range(10)}
df = pd.DataFrame(data, index=date_range)
print(df,'\n')
# 월별 데이터 합계 계산
monthly_sum = df.resample('M').sum()
print(monthly_sum)

            value
2022-01-01      0
2022-01-02      1
2022-01-03      2
2022-01-04      3
2022-01-05      4
2022-01-06      5
2022-01-07      6
2022-01-08      7
2022-01-09      8
2022-01-10      9

            value
2022-01-31     45

In [43]:
# Q. 365일간 일당을 성과에 따라서 50~100 달러를 받는다 월별 합계를 구하세요
import numpy as np

date_range = pd.date_range(start = '2022-01-01', periods=365, freq = 'D')
data = {'value': np.random.randint(50,100,365)}
df = pd.DataFrame(data, index=date_range)
monthly_sum = df.resample('M').sum()
print(monthly_sum)

            value
2022-01-31   2369
2022-02-28   2133
2022-03-31   2219
2022-04-30   2279
2022-05-31   2404
2022-06-30   2167
2022-07-31   2327
2022-08-31   2204
2022-09-30   2200
2022-10-31   2244
2022-11-30   2302
2022-12-31   2267

In [52]:
data = {'date':['2022-01-01','2022-01-02','2022-01-03'], 'value':[1,2,3]}
df = pd.DataFrame(data)
print(df,'\n')
df['date'] = pd.to_datetime(df['date'])

# pandas의 datetime 형식 데이터는 다양한 속성에 접근할 수 있다 연도, 월, 일 요일 등을 쉽게 추출
# df.index.year
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['day_of_week'] = df['date'].dt.dayofweek

# 결과 출력
print(df)

         date  value
0  2022-01-01      1
1  2022-01-02      2
2  2022-01-03      3

        date  value  year  month  day  day_of_week
0 2022-01-01      1  2022      1    1            5
1 2022-01-02      2  2022      1    2            6
2 2022-01-03      3  2022      1    3            0

In [76]:
# Google Colab에서 파일 업로드
from google.colab import files
uploaded = files.upload()

# 업로드된 파일을 데이터프레임으로 읽기
file_path = list(uploaded.keys())[0]
df = pd.read_csv(file_path)

Saving stock-data.csv to stock-data (1).csv

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     object
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), object(1)
memory usage: 1.1+ KB

In [78]:
df['New_Date'] = pd.to_datetime(df['Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      20 non-null     object
 1   Close     20 non-null     int64
 2   Start     20 non-null     int64
 3   High      20 non-null     int64
 4   Low       20 non-null     int64
 5   Volume    20 non-null     int64
 6   New_Date  20 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 1.2+ KB

In [79]:
# 새로운 날짜 열에서 연도, 월, 일 정보를 추출하여 새로운 열을 추가하는 작업을 수행
df.drop('Date',axis=1,inplace=True)
# dt 접근자
df['year'] = df['New_Date'].dt.year
df['month'] = df['New_Date'].dt.month
df['day'] = df['New_Date'].dt.day
df.head()

   Close  Start   High    Low  Volume   New_Date  year  month  day
0  10100  10850  10900  10000  137977 2018-07-02  2018      7    2
1  10700  10550  10900   9990  170253 2018-06-29  2018      6   29
2  10400  10900  10950  10150  155769 2018-06-28  2018      6   28
3  10900  10800  11050  10500  133548 2018-06-27  2018      6   27
4  10800  10900  11000  10700   63039 2018-06-26  2018      6   26

In [70]:
# Task1. 주어진 df의 날짜 리스트를 datetime 형식으로 변환하고, 변환된 데이터프레임의 년도, 월, 일 열을 추가하시오.
import pandas as pd

# 날짜 문자열 리스트
date_list = ['2023-01-01', '2023-02-15', '2023-03-30']

# 데이터프레임 생성
df = pd.DataFrame(date_list, columns=['date'])
print(df,'\n')
df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
print(df)

         date
0  2023-01-01
1  2023-02-15
2  2023-03-30

        date  year  month  day
0 2023-01-01  2023      1    1
1 2023-02-15  2023      2   15
2 2023-03-30  2023      3   30

In [2]:
# Task2. 주어진 월간 데이터를 타임스탬프로 변환하고, 변환된 결과에서 시간을 제외한 날짜만 출력하시오.
import pandas as pd
import datetime

# 문자열을 Period로 변환
period_data = pd.Series(['2023-01', '2023-02', '2023-03'], name='period')
print(period_data,type(period_data))
period_data = pd.to_datetime(period_data)
print(period_data.dt.date)

0    2023-01
1    2023-02
2    2023-03
Name: period, dtype: object <class 'pandas.core.series.Series'>
0    2023-01-01
1    2023-02-01
2    2023-03-01
Name: period, dtype: object

In [3]:
# 문자열을 Period로 변환
period_data = period_data.astype('period[M]')
print(period_data)
# Period를 Timestampe로 변환
timestamp_data = period_data.apply(lambda x : x.to_timestamp())

# 날짜만 출력
print(timestamp_data)

0    2023-01
1    2023-02
2    2023-03
Name: period, dtype: period[M]
0   2023-01-01
1   2023-02-01
2   2023-03-01
Name: period, dtype: datetime64[ns]

In [108]:
# Task3. 주어진 날짜 데이터 시리즈를 분기로 변환하고, 각 분기별로 데이터의 개수를 출력하세요.
import pandas as pd

# 날짜 데이터 시리즈
date_series = pd.Series(pd.date_range('2023-01-01', '2023-12-31', freq='M'))
date_series = pd.to_datetime(date_series)
print(date_series,'\n')
# df = pd.DataFrame('date'= date_series)
# df.reset_index
# quarterly_data = df.resample('Q').sum()
# print(quarterly_data)
quarter_data = date_series.dt.to_period('Q')
print(quarter_data)


# quarter_data.resample('Q').sum()

0    2023-01-31
1    2023-02-28
2    2023-03-31
3    2023-04-30
4    2023-05-31
5    2023-06-30
6    2023-07-31
7    2023-08-31
8    2023-09-30
9    2023-10-31
10   2023-11-30
11   2023-12-31
dtype: datetime64[ns]

0     2023Q1
1     2023Q1
2     2023Q1
3     2023Q2
4     2023Q2
5     2023Q2
6     2023Q3
7     2023Q3
8     2023Q3
9     2023Q4
10    2023Q4
11    2023Q4
dtype: period[Q-DEC]

In [107]:
# 날짜 데이터를 분기로 변환
quarter_data = date_series.dt.to_period('Q')

# 각 분기별 데이터 개수 세기
# value_counts() : Series에서 각 고유한 값의 빈도를 계산
quarter_counts = quarter_data.value_counts().sort_index()

print(quarter_counts)

2023Q1    3
2023Q2    3
2023Q3    3
2023Q4    3
Freq: Q-DEC, Name: count, dtype: int64