## 자료형 - Tuple

- 튜플은 변경할 수 없는(immutable)순서가 있는 컬렉션
- 프로그램에서 그 값이 항상 변하지 않아야되는 경우 사용

In [24]:
tuple1 = (1,2,3,4,5)
tuple2 = ('a','b','c')
tuple3 = (1,'a','abc',[1,2,3,4,5], ['a','b','c'])

print(tuple1)
print(tuple2[2])
print(tuple3[3][2])

(1, 2, 3, 4, 5)
c
3

In [25]:
tuple1 = (1,2,3,4,5)
# tuple1[0] = 0
print(tuple1)

# 리스트와 달리 튜플은 요소 값을 변경할 수 없다(수정 불가능)

list1 = [1,2,3,4,5]
print(list1)
list1[0] = 0
print(list1)

(1, 2, 3, 4, 5)
[1, 2, 3, 4, 5]
[0, 2, 3, 4, 5]

In [86]:
tuple1 = (1,2,3,4,5)
lis = list(tuple1)
print(lis)
lis.append(6)
print(lis)
tuple1 = tuple(lis)
print(tuple1)
lis = list(tuple1)
print(lis)
del lis[0]
print(lis)
tuple1 = tuple(lis)
print(tuple1)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
(1, 2, 3, 4, 5, 6)
[1, 2, 3, 4, 5, 6]
[2, 3, 4, 5, 6]
(2, 3, 4, 5, 6)

In [26]:
li1 = [1]
print(li1)

tu1 = (1,)
tu2 = (1)
print(tu1,type(tu1))
print(tu2, type(tu2))
# 리스트와 달리 튜플은 한 개의 값을 출력할 때는 값 뒤에 콤마를 함께 사용해야한다

[1]
(1,) <class 'tuple'>
1 <class 'int'>

In [ ]:
tu2 = 1,2,3
print(tu2, type(tu2))
# 소괄호를 생략해도 tuple형식으로 출력된다(튜플의 패킹)
# 문자형도 가능

In [28]:
print([1,2,3]+[4,5,6])
print((1,2,3)+(4,5,6))
# 리스트와 튜플끼리 각 각 더하면 리스트, 튜플형식으로 연결된다

[1, 2, 3, 4, 5, 6]
(1, 2, 3, 4, 5, 6)

In [29]:
in1 = (1)
tu1 = (1,)
# print(in1+tu1) #int와 tuple은 + 불가능
tu2 = (1,2)
print(tu1+tu2)

(1, 1, 2)

In [30]:
li1 = [1,2,3,4,5]
in1 = (1)
# print(li1+in1) #리스트도 불가능
print(li1*in1)
li2=[2,3,4,5,6]
# print(li1*li2) #리스트끼리 곱하기 불가능

[1, 2, 3, 4, 5]

In [31]:

# 튜플에서 각 값을 변수에 할당
colors = ('red','green','blue')
r,g,b = colors
print(r,g,b)
# 각 항목끼리 담겨진 갯수가 같아야한다

red green blue

In [34]:
# 함수에서 여러 값을 반환할 때 튜플을 사용하는 것이 일반적입니다
# 주어진 리스트의 총합과 평균을 동시에 반환하는 함수를 작성하세요
# numbers = [10,20,30,40,50]
def calculate_sum_and_average(numbers):
    add = sum(numbers)
    ave = sum(numbers) / len(numbers)
    return (add,ave)

numbers = [10,20,30,40,50]
# print(calculate_sum_and_average(numbers))
total, average = calculate_sum_and_average(numbers)
# ca..(numbers)에 값이 리턴값으로 값이 두개 저장되어 있으므로 변수를 두개에 저장한다면
# 각 값을 변수에 할당하게 된다 리턴값 순서에 따라  합계는 total에 평균은 average에 저장하게 된다
print(f"리스트에 총합은 {total}이고, 평균은 {average}입니다")

리스트에 총합은 150이고, 평균은 30.0입니다

## 자료형 - 사전

- 키와 값을 하나의 요소로 하는 순서가 없는 집합

In [37]:
di1 = {'a':1,'b':2,'c':3}
print(di1,type(di1))
print(di1['a'])

print(di1.keys())
print(di1.values())
print(di1.items()) #튜플형태로 출력

{'a': 1, 'b': 2, 'c': 3} <class 'dict'>
1
dict_keys(['a', 'b', 'c'])
dict_values([1, 2, 3])
dict_items([('a', 1), ('b', 2), ('c', 3)])

In [38]:
di1['d']=4
print(di1)
# 시퀀스가 아닌 대신에 key값으로 인덱스를 정하여 추가할 수 있다

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [39]:
di1['b'] = 4
print(di1)

{'a': 1, 'b': 4, 'c': 3, 'd': 4}

In [42]:
# del di1['b']

print(di1)

{'a': 1, 'c': 3, 'd': 4}

In [70]:
# d = {'a':1,'b':7,'c':3,'d':4}
# b의 값을 확인하면서 그 값을 삭제하세요

d = {'a':1,'b':7,'c':3,'d':4}
print(d['b'])
print(d.pop('b'))
print(d)
# pop 형식 : 변수명.pop(키값)

7
7
{'a': 1, 'c': 3, 'd': 4}

In [53]:
# 학생의 이름과 점수를 튜플로 묶은 리스트가 있습니다 이 리스트를 사용해 학생이름을 키로 점수를 값으로 하는 딕셔너리를 생성하고
# 출력하세요 [("Tom":85),("Jane":90),("Bob":74)]

li1 = [("Tom",85),("Jane",90),("Bob",74)]
print(li1)
di1 = dict(li1)
print(di1)
print(di1.keys())
print(di1.values())

[('Tom', 85), ('Jane', 90), ('Bob', 74)]
{'Tom': 85, 'Jane': 90, 'Bob': 74}
dict_keys(['Tom', 'Jane', 'Bob'])
dict_values([85, 90, 74])

In [73]:
# 튜플의 불변성 때문에 튜플은 딕셔너리의 키로 사용될 수 있습니다 주어진 위치 좌표 리스트에서 각 위치가 몇번 나타나는지 계산하는
# 딕셔너리를 만드세요
positions = [(1,1), (2,2), (1,1), (3,3), (2,2)]
li1 = [i for i,va in positions]
print(positions)
posit = dict(positions)
print(posit)

[(1, 1), (2, 2), (1, 1), (3, 3), (2, 2)]
{1: 1, 2: 2, 3: 3}

In [78]:
from collections import Counter
positions_data = Counter(positions)
print(positions_data)
di1 = dict(positions_data)
print(di1)
print(di1.keys())

Counter({(1, 1): 2, (2, 2): 2, (3, 3): 1})
{(1, 1): 2, (2, 2): 2, (3, 3): 1}
dict_keys([(1, 1), (2, 2), (3, 3)])

In [90]:
# 위치 좌표의 리스트
positions = [(1,1), (2,2), (1,1), (3,3), (2,2)]

# 각 위치의 출현 횟수를 저장할 딕셔너리
position_count = {}

for pos in positions :
    if pos in position_count :
        position_count[pos] += 1
    else : #[pos]를 사용하여 인덱싱을 하고 인덱싱 한 곳에 값을 넣는다
        position_count[pos] = 1

print(position_count)

{(1, 1): 2, (2, 2): 2, (3, 3): 1}

## 자료형 - 집합, set

- 중복을 허용하지 않으며 순서가 없다

In [91]:
s1 = set([1,2,5,3,4])
s2 = set("Hello")
print(s1,type(s1))
print(s2,type(s2))

{1, 2, 3, 4, 5} <class 'set'>
{'o', 'e', 'l', 'H'} <class 'set'>

In [92]:
# 순서가 없으므로 인덱스 불가능 -> 리스트로 형변환 후 값 추출
li1 = list(s1)
print(li1)
print(li1[1])

[1, 2, 3, 4, 5]
2

In [95]:
# set s2에서 l만 출력하기
li2 = list(s2)
print(li2)
print(li2[2])

['o', 'e', 'l', 'H']
l

In [121]:
# 주어진 리스트에서 중복 요소를 제거하고 결과 출력
nums = [1,2,2,3,4,4,4,5]
print(nums)
se1 = set(nums)
print(se1)

[1, 2, 2, 3, 4, 4, 4, 5]
{1, 2, 3, 4, 5}

In [129]:
a = []

for i in nums :
    if i not in a :
        a.append(i)
    else :
        pass
print(a)

[1, 2, 3, 4, 5]

In [133]:

def list_dupication(data):
    lis1 = []
    for i in data:
        if i not in lis1:
            lis1.append(i)
        else:
            pass

nums = [1,2,2,3,4,4,4,5]
list_dupication(nums)

In [103]:
# s1,s2의 합집합과 교집합을 각각리스트로 출력
s1 = set([1,2,3,4,5,6])
s2 = set([4,5,6,7,8,9])

li4 = [i for i in s1 for j in s2 if i == j]
print(li4)

lii = list(s1)
liii = list(s2)
add = lii + liii
print(add)
se3 = set(add)
print(se3)

[4, 5, 6]
[1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9]
{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [106]:
# set에서만 | &을 사용할 수 있다
print(list(s1|s2)) #합집합
print(list(s1&s2)) #교집합

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[4, 5, 6]

In [111]:
# 첫번째 집합에서 두번재 집합의 요소를 제외한 차집합을 구하고 출력
set1 = {1,2,3,4,5}
set2 = {4,5,6,7}

print(set1 - set2)
print(set1.difference(set2))
print((set1|set2)-(set1&set2))

{1, 2, 3}
{1, 2, 3}
{1, 2, 3, 6, 7}

In [113]:
# Task1_0426. 주어진 리스트에서 중복된 요소를 제외하고 고유한 요소의 개수를 세는 프로그램을 작성하세요.

data = [1, 2, 2, 3, 4, 4, 4, 5]
se1 = set(data)
print(set1)
print(len(set1))

{1, 2, 3, 4, 5}
5

In [117]:
# Task2_0426. 두 개의 리스트에서 공통으로 나타나는 요소들을 찾아 리스트로 반환하는 프로그램을 작성하세요.

# 예시 입력: list1 = [1, 2, 3, 4, 5], list2 = [4, 5, 6, 7, 8]

# 예시 출력: [4, 5]

def intersaction_factor(li1,li2):
       s1 = set(li1)
       s2 = set(li2)
       return list(s1 & s2)

li1 = [1,2,3,4,5]
li2 = [4,5,6,7,8]
result = intersaction_factor(li1,li2)
print(result)

[4, 5]

## 자료형 - 논리(Bool) True와 False

- 파이썬에서 참과 거짓을 나타내는 상수. True는 1, False는 0의 값을 가짐
- 조건을 판단해서 그 조건이 참이면 True, 거짓이면 False를 retrun

In [115]:
print(bool(0))
print(bool(1))
print(bool(''))
print(bool([d]))
print(bool(200))
print(bool([]))

False
True
False
True
True
False

In [118]:
# 관계연산자
x = 1; y = 2
str1 = 'abc' ; str2 = 'python'
print(x == y)
print(x != y)
print(str1 == str2)
print(str2 == 'python')
# 문자를 비교할 때는 아스키코드 ASCII값에서 a가 97이고 p가 112이므로 True를 반환한다
print(str1 <str2)

False
True
False
True
True

In [130]:
# 논리연산자
print(True and False)
print(True or False)
print(not True)
print(not False)

False
True
False
True

In [230]:
# Task3_0426. 주어진 숫자 리스트에서 특정 값보다 큰 요소가 하나라도 존재하는지 검사하고, 그 결과를 불 값으로 반환하는 함수를 작성하세요.

# - numbers = [1, 2, 3, 10, 20]
# - threshold = 15

def max_number(numbers, threshold):
    for i in numbers:
        if i > threshold :
            return True
    return False

numbers = [1,2,3,10]
threshold = 15
print(max_number(numbers,threshold))
# 리스트안에서 그 값보다 하나라도 크다면 참
# return 관계나 논리연산자

False

In [219]:
for i in numbers :
    print(i > threshold)
numbers = [1, 2, 3]
threshold = 15

False
False
False

In [233]:
# Task4_0426. 주어진 문자열이 특정 문자열을 포함하는지 확인하고 결과를 불 값으로 반환하는 함수를 작성하세요.

text = "hello world"
substring = "world"

def string_cheak(text):
    text1 = text.split()
    for i in text1 :
        if i == substring :
            return True
    return False

print(string_cheak(text))

True

In [237]:
# Task5_0426. 주어진 연도가 윤년인지 판별하는 함수를 작성하세요. 윤년은 다음의 조건을 만족해야 합니다:
# - 4로 나누어 떨어진다.
# - 100으로 나누어 떨어지지 않거나, 400으로 나누어 떨어지면 윤년이다.

# year = 2020

# True
def year_check(year):
    if (year % 4 == 0) and (year % 100 != 0 or year % 400 == 0):
        return True
    return False

year = 2022
print(year_check(year))

False

#### 파이썬에서 들여쓰기

- 파이썬에는 실행 코드 부분을 묶어주는 {} 괄호가 없다.
- 대신 들여쓰기(indentation)로 {}를 대신한다.
- 제어문이나 함수이름, 클래스 이름 뒤에 콜론(':')으로 제어문, 함수이름, 클래스 이름의 끝을 표시하며 ':' 다음에 실행 코드를 작성

In [138]:
li = ['a','b','c']
if 'a' in li :
    print('aa가 li에 잇슴')
else:
    print("a가 li에 없음")

aa가 li에 잇슴

### 사용자 함수

In [141]:
def add(a,b,c):
    return a+b+c

print(add(1,2,3))

6

In [148]:
def mul(a,b,c):
    return a*b*c

print(mul(5,6,7))

210

In [160]:
# 뺄셈 나눗셈을 수행하는 사용자 함수 작성
def multi(a, b):
    minus = a - b
    sksnrl = a / b
    return (minus, sksnrl)

print(multi(10,5))

(5, 2.0)

In [161]:
# 뺄셈
def subtract(a,b,c):
    return a - b - c

print(subtract(10,2,2))

6

In [171]:
# 나눗셈
def divide(a,b,c):
    if b == 0 or c == 0:
        return "Error : Division by Zero"
    else :
        return a/b/c

print(round(divide(10,5,9),3))

0.222

In [175]:
class AddMul:
    def add(self,n1,n2):
        return n1+n2
    def mul(self,n1,n2):
        return n1 * n2

obj1 = AddMul() #객체
print(obj1.add(1,4))

5

In [177]:
# Task6_0426. Calculator 클래스를 작성하고 4칙연산을 수행하는 객체 4개를 작성하여 결과를 출력하세요..

class Calculator:
    def add(self,n1,n2):
        return n1 + n2
    def subt(self,n1,n2):
        return n1 - n2
    def mul(self,n1,n2):
        return n1 * n2
    def divi(self,n1,n2):
        return n1 / n2

ob1 = Calculator()
print(ob1.add(5,7))
ob2 = Calculator()
print(ob2.subt(2,7))
ob3 = Calculator()
print(ob3.mul(5,2))
ob4 = Calculator()
print(ob4.divi(9,3))

12
-5
10
3.0

In [238]:
# Task7_0426. 다음 과제를 수행하세요.
# - 사용자로 부터 텍스트를 입력 받는다.
# - 문자을 단어 단위로 분리 : split()
# - 단어의 빈도수를 저장할 딕셔너리를 생성
# - 각 단어의 빈도 수를 계산(for 문 / if else문)
# - 결과 출력

# [ 예시 ]

# 문장을 입력하세요: I love apple. I love orange. Apple is tasty

# {'i': 2, 'love': 2, 'apple.': 1, 'orange.': 1, 'apple': 1, 'is': 1, 'tasty': 1}
text = input("텍스트를 입력하세요 : ")
text_lower = text.lower()
text_divide = text_lower.split()

dic = {}
for i in text_divide:
    if i in dic:
        dic[i] += 1
    else :
        dic[i] = 1
print(dic)

텍스트를 입력하세요 : i love apple. Apple is tasty
{'i': 1, 'love': 1, 'apple.': 1, 'apple': 1, 'is': 1, 'tasty': 1}